"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cL-px-6axNlYAUHCFClz139FGINou9d1
"""

import pandas as pd

restaurant_name = "Pizza Hut"
restaurant_location = "2, NH 58, Civil Lines, Civil Lines, Roorkee, Uttarakhand 247667, Roorkee Locality, Roorkee"
restaurant_contact = "+919643105647"
operating_hours = "10:00 AM - 11:00 PM"
dining_rating = 4.2
delivery_rating = 4.1

df = pd.read_csv('/content/pizzahut_roorkee_menu.csv')

df['restaurant name'] = restaurant_name
df['location'] = restaurant_location
df['contact'] = restaurant_contact
df['operating hour'] = operating_hours
df['dining rating'] = dining_rating
df['delivery rating'] = delivery_rating

df.to_csv('Pizza_Hut_roorkee_menu_with_details.csv', index=False)